task_for_review
levochkinajuli/Sprint_5 pull request #1
Opened 2023-11-04 15:59 UTC by levochkinajuli

2023-11-07 07:21 UTC, kadirovgm requested changes

2023-11-07 07:21 UTC, kadirovgm commented on conftest.py
> +
нужно исправить: эти все данные лучше вынести в отдельный файл data.py и группирвоать по классам данным, как фикстуры не нужно передавать тестовые данные

в conftest.py храним только фикстуры, которые должны быть выполнены до или после тестов

2023-11-07 07:21 UTC, kadirovgm commented on conftest.py
> +
- Нужно исправить: необходимо добавить самую важную фикстуру, отвечающую за `setup` и `teardown`

Пример:

```
@pytest.fixture()
def driver():
    driver = webdriver.Chrome()
    driver.get(<url main page>)

    yield driver
    driver.quit()
```

2023-11-07 07:21 UTC, kadirovgm commented on conftest.py
> +
можно лучше: также предлагаю сделать фикстуру для авторизации

2023-11-07 07:21 UTC, kadirovgm commented on locators.py
> +    def locator_name():
нужно исправить: не нужно для каждого локатора создавать отдельный метод, можно указать локаторы как глоальные переменные классов

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        time.sleep(3)
нужно исправить: не стоит пользоваться такими явными ожиданиями как sleep()

в противном случае, если тестов будет сотни, то такие слипы могут удлинять время прохождения тестов в разы - что плохо скажется на скорости тестирования

Существуют более удобные методы, которые помогут написать код, ожидающий ровно столько, сколько необходимо. WebDriverWait в комбинации с ExpectedCondition является одним из таких способов.

```
element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
    )
```

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        driver.get('https://stellarburgers.nomoreparties.site/register')
нужно исправить: тестовые статичные данные лучше выносить в отдельный файл типа [data.py](http://data.py/) или [urls.py](http://urls.py/)
Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений.

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        driver.find_element(*RegistrationLocators.locator_name()).send_keys(name)
можно лучше: повторяющиеся строки в коде (как тут заполнение регистрационных и авторизационных полей в нескольких тестах) стоит вынести в отдельные функции и, например, поместить в файл helpers.py, чтобы не плодить в коде одинаковые строки, которые повышают шанс возникновения багов, и усложняют поддержку и масштабирование тестов

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        driver.quit()
нужно исправить: teardown метод вынести в фикстуру

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        assert 'login' in driver.current_url
нужно исправить: стоит добавить более явную проверку, которая гарантирует, что регистрация успешна, например, по наличию какого-либо значимого элемента страницы

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_3_lk.py
> +        assert 'profile' in driver.current_url
нужно исправить: здесь и ниже - добавить явные проверки, гарантирующие успешность теста

2023-11-07 07:21 UTC, kadirovgm commented on tests/test_1_registration.py
> +        driver = webdriver.Chrome()
нужно исправить: здесь и ниже - вынести setup методы из тестов в фикстуру

2023-11-07 14:40 UTC, levochkinajuli commented on tests/test_1_registration.py
> +        driver = webdriver.Chrome()
1.	Локаторы исправила: убрала методы, указала как глобальные переменные класса.
2.	Добавила фикстуру, отвечающую за setup и teardown.
3.	Из conftest.py перенесла данные в файл data.py.
4.	Поменяла ожидание sleep() на WebDriverWait.
5.	Тесты поправила.
6.	Фикстура для входа – я не написала, но могу поправить, если это критично.

2023-11-07 14:40 UTC, levochkinajuli commented
1.	Локаторы исправила: убрала методы, указала как глобальные переменные класса.
2.	Добавила фикстуру, отвечающую за setup и teardown.
3.	Из conftest.py перенесла данные в файл data.py.
4.	Поменяла ожидание sleep() на WebDriverWait.
5.	Тесты поправила.
6.	Фикстура для входа – я не написала, но могу поправить, если это критично.

2023-11-07 17:19 UTC, kadirovgm requested changes

2023-11-07 17:19 UTC, kadirovgm commented on data.py
> +NAME = 'vasia'
можно лучше: лучше сгруппировать данные по классам

2023-11-07 17:19 UTC, kadirovgm commented on locators.py
> +
нужно исправить: добавь локаторы в классы по экранам

- класс с локаторами лучше разделить на несколько: например `AuthPageLocators`, `MainPageLocators`
Сейчас это не критично, но в будущем это точно стоит сделать, так как таким образом ты не будешь импортить лишние локаторы в файл с тестами на экран авторизации. Т.е. у каждой страницы должен быть свой класс с локаторами.
    
    При таком подходе код станет лаконичнее, легко поддерживаемой. Ведь у экрана авторизации и у экрана главной могут быть свои NEXT_BUTTON например. Тогда можно будет легко оба обозвать именно так:
    `MainPageLocators.NEXT_BUTTON` и `AuthPageLocators.NEXT_BUTTON`

2023-11-07 17:19 UTC, kadirovgm commented on conftest.py
> +
нужно исправить: этот файл наверное теперь удалить надо?

2023-11-07 17:19 UTC, kadirovgm commented on tests/conftest.py
> +
нужно исправить: все правильно, только conftest.py - это не тесты, так что его вынеси в каталоге на один раздел выше, в папке tests храним только тесты

2023-11-07 17:19 UTC, kadirovgm commented on tests/test_1_registration.py
> +        assert browser.find_element(*locators.BUTT_ENTER).text == 'Войти'
супер!

2023-11-07 17:19 UTC, kadirovgm commented on tests/test_4_constructor.py
> +
нужно исправить: во всех тестах ниже добавь asserts

2023-11-07 17:19 UTC, kadirovgm commented on urls.py
> +
можно лучше: добавь класс Urls()

2023-11-07 17:19 UTC, kadirovgm commented on tests/conftest.py
> +    driver.get('https://stellarburgers.nomoreparties.site/')
нужно исправить: почему не берешь данные из файлы urls.py ?

2023-11-08 06:16 UTC, levochkinajuli commented
1.	conftest.py – вынесла на раздел выше.
2.	def browser – добавила данные из urls
3.	test_4_constructor.py – добавила asserts
4.	сгруппировала данные по классам.
5.	сгруппировала локаторы по классам.

2023-11-08 19:40 UTC, kadirovgm approved these changes

2023-11-09 07:16 UTC, merged